### ISSUE TITLE
Not able to clone the venia-sample-data-modules repository

### ISSUE THREAD

**Issue by hiren2615** [AdobeDocs/commerce-pwa-studio#190] opened 2023-06-02 06:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

**Visit this URL:** https://developer.adobe.com/commerce/pwa-studio/metapackages/venia-sample-data/

Check the below installation step 3.
3. Clone the venia-sample-data-modules repository into your vendor directory within ext:
git clone git@github.com:magento/venia-sample-data-modules.git ext/magento/venia-sample-data-modules

I am not able to clone that repo. The above git command should work.

### Actual behavior

git clone git@github.com:magento/venia-sample-data-modules.git ext/magento/venia-sample-data-modules

The above git command is not working. it gives the below error.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

### Steps to reproduce

git clone git@github.com:magento/venia-sample-data-modules.git ext/magento/venia-sample-data-modules

The above git command should work.

### Environment

- Browser:
- OS:

**Comment by jeff-matthews** [comment] 2023-07-14 15:50
Sorry about that @hiren2615. I can confirm that repo doesn't seem to exist anymore... I think this might be the right repo to use instead: https://github.com/magento/module-configurable-sample-data-venia

**Comment by jeff-matthews** [comment] 2023-12-08 14:15
Duplicate of #154 

Will track progress in #154

**Closed as completed by jeff-matthews** 2023-12-08 14:15 UTC
Labels: bug
